<?
$AKHZ = @@AKHZ;
$ALARM = @@ALARM;
$APP_UID = @@APP_UID; 
$DASTGAHEJRAI = @@DASTGAHEJRAI;
$DEADLINE_ASNAD = @@DEADLINE_ASNAD;
$DEADLINE_PASOKH = @@DEADLINE_PASOKH;
$MABLAGH = @@MABLAGH;
$MOZAYEDE_SHOMARE = @@MOZAYEDE_SHOMARE;
$NAHVE_SHERKAT = @@NAHVE_SHERKAT;
$NAME = @@NAME;
$TAHVIL_BAR = @@TAHVIL_BAR;
$TYPE = @@TYPE;
$ZEMANAT_NAMEH = @@ZEMANAT_NAMEH;
$ZEMANAT_NAMEH_2 = @@ZEMANAT_NAMEH_2;

// Insert the feedback into the database using APP_UID as the identifier
$insert_query = "INSERT INTO PRC_DB_MOZAYEDAT_MONAGHESAT (APP_UID, AKHZ, ALARM, DASTGAHEJRAI, DEADLINE_ASNAD, DEADLINE_PASOKH, MABLAGH, MOZAYEDE_SHOMARE, NAHVE_SHERKAT, NAME, TAHVIL_BAR, TYPE, ZEMANAT_NAMEH, ZEMANAT_NAMEH_2) VALUES ('$APP_UID', '$AKHZ', '$ALARM', '$DASTGAHEJRAI', '$DEADLINE_ASNAD', '$DEADLINE_PASOKH', '$MABLAGH', '$MOZAYEDE_SHOMARE', '$NAHVE_SHERKAT', '$NAME', '$TAHVIL_BAR', '$TYPE', '$ZEMANAT_NAMEH', '$ZEMANAT_NAMEH_2')";
executeQuery($insert_query);

// Clear the session variables
unset(@@AKHZ);
unset(@@ALARM);
unset(@@APP_UID);
unset(@@DASTGAHEJRAI);
unset(@@DEADLINE_ASNAD);
unset(@@DEADLINE_PASOKH);
unset(@@MABLAGH);
unset(@@MOZAYEDE_SHOMARE);
unset(@@NAHVE_SHERKAT);
unset(@@NAME);
unset(@@TAHVIL_BAR);
unset(@@TYPE);
unset(@@ZEMANAT_NAMEH);
unset(@@ZEMANAT_NAMEH_2);
