<?
// before get started, we should know column names,
// here is SQL code to do so :
    //SELECT COLUMN_NAME
    //FROM INFORMATION_SCHEMA.COLUMNS
    //WHERE TABLE_SCHEMA = 'your_database_name' AND TABLE_NAME = 'your_table_name';
// her is column names :
// APP_NUMBER
// APP_STATUS
// APP_UID
// GROUH
// MAKAN
// MOSHAKHASE
// ONVAN_AMVAL
// PELAK_AMVAL
// SANAD
// TAHVIL_GIRANDE
// TARIKH
// TEDAD
// TYPE
// VASZIYAT_ESTEFADE

$APP_UID = @@APP_UID;
$GROUH = @@GROUH;
$MAKAN = @@MAKAN;
$MOSHAKHASE = @@MOSHAKHASE;
$ONVAN_AMVAL = @@ONVAN_AMVAL;
$PELAK_AMVAL = @@PELAK_AMVAL;
$SANAD = @@SANAD;
$TAHVIL_GIRANDE = @@TAHVIL_GIRANDE;
$TARIKH = @@TARIKH;
$TEDAD = @@TEDAD;
$VASZIYAT_ESTEFADE = @@VASZIYAT_ESTEFADE;



$insert_query = "INSERT INTO ??? (APP_UID, GROUH, MAKAN, MOSHAKHASE, ONVAN_AMVAL, PELAK_AMVAL, SANAD, TAHVIL_GIRANDE, TARIKH, TEDAD, VASZIYAT_ESTEFADE) VALUES ('$APP_UID', '$GROUH', '$MAKAN', '$MOSHAKHASE', '$ONVAN_AMVAL', '$PELAK_AMVAL', '$SANAD', '$TAHVIL_GIRANDE', '$TARIKH', '$TEDAD', '$VASZIYAT_ESTEFADE')";
executeQuery($insert_query);

// Clear the session variables
unset(@@APP_UID);
unset(@@GROUH);
unset(@@MAKAN);
unset(@@MOSHAKHASE);
unset(@@ONVAN_AMVAL);
unset(@@PELAK_AMVAL);
unset(@@SANAD);
unset(@@TAHVIL_GIRANDE);
unset(@@TARIKH);
unset(@@TEDAD);
unset(@@VASZIYAT_ESTEFADE);
